=begin comment

EVE Swagger Interface

An OpenAPI for EVE Online

OpenAPI spec version: 0.4.2.dev22

Generated by: https://github.com/swagger-api/swagger-codegen.git

=end comment

=cut

#
# NOTE: This class is auto generated by the swagger code generator program. 
# Do not edit the class manually.
# Ref: https://github.com/swagger-api/swagger-codegen
#
package EVE::ESI::Client::Object::GetCharactersCharacterIdChatChannels200Ok;

require 5.6.0;
use strict;
use warnings;
use utf8;
use JSON qw(decode_json);
use Data::Dumper;
use Module::Runtime qw(use_module);
use Log::Any qw($log);
use Date::Parse;
use DateTime;

use base ("Class::Accessor", "Class::Data::Inheritable");


#
#200 ok object
#
# NOTE: This class is auto generated by the swagger code generator program. Do not edit the class manually.
# REF: https://github.com/swagger-api/swagger-codegen
#

=begin comment

EVE Swagger Interface

An OpenAPI for EVE Online

OpenAPI spec version: 0.4.2.dev22

Generated by: https://github.com/swagger-api/swagger-codegen.git

=end comment

=cut

#
# NOTE: This class is auto generated by the swagger code generator program. 
# Do not edit the class manually.
# Ref: https://github.com/swagger-api/swagger-codegen
#
__PACKAGE__->mk_classdata('attribute_map' => {});
__PACKAGE__->mk_classdata('swagger_types' => {});
__PACKAGE__->mk_classdata('method_documentation' => {}); 
__PACKAGE__->mk_classdata('class_documentation' => {});

# new object
sub new { 
    my ($class, %args) = @_; 

	my $self = bless {}, $class;
	
	foreach my $attribute (keys %{$class->attribute_map}) {
		my $args_key = $class->attribute_map->{$attribute};
		$self->$attribute( $args{ $args_key } );
	}
	
	return $self;
}  

# return perl hash
sub to_hash {
    return decode_json(JSON->new->convert_blessed->encode( shift ));
}

# used by JSON for serialization
sub TO_JSON { 
    my $self = shift;
    my $_data = {};
    foreach my $_key (keys %{$self->attribute_map}) {
        if (defined $self->{$_key}) {
            $_data->{$self->attribute_map->{$_key}} = $self->{$_key};
        }
    }
    return $_data;
}

# from Perl hashref
sub from_hash {
    my ($self, $hash) = @_;

    # loop through attributes and use swagger_types to deserialize the data
    while ( my ($_key, $_type) = each %{$self->swagger_types} ) {
    	my $_json_attribute = $self->attribute_map->{$_key}; 
        if ($_type =~ /^array\[/i) { # array
            my $_subclass = substr($_type, 6, -1);
            my @_array = ();
            foreach my $_element (@{$hash->{$_json_attribute}}) {
                push @_array, $self->_deserialize($_subclass, $_element);
            }
            $self->{$_key} = \@_array;
        } elsif (exists $hash->{$_json_attribute}) { #hash(model), primitive, datetime
            $self->{$_key} = $self->_deserialize($_type, $hash->{$_json_attribute});
        } else {
        	$log->debugf("Warning: %s (%s) does not exist in input hash\n", $_key, $_json_attribute);
        }
    }
  
    return $self;
}

# deserialize non-array data
sub _deserialize {
    my ($self, $type, $data) = @_;
    $log->debugf("deserializing %s with %s",Dumper($data), $type);
        
    if ($type eq 'DateTime') {
        return DateTime->from_epoch(epoch => str2time($data));
    } elsif ( grep( /^$type$/, ('int', 'double', 'string', 'boolean'))) {
        return $data;
    } else { # hash(model)
        my $_instance = eval "EVE::ESI::Client::Object::$type->new()";
        return $_instance->from_hash($data);
    }
}



__PACKAGE__->class_documentation({description => '200 ok object',
                                  class => 'GetCharactersCharacterIdChatChannels200Ok',
                                  required => [], # TODO
}                                 );

__PACKAGE__->method_documentation({
    'allowed' => {
    	datatype => 'ARRAY[GetCharactersCharacterIdChatChannelsAllowed]',
    	base_name => 'allowed',
    	description => 'allowed array',
    	format => '',
    	read_only => '',
    		},
    'blocked' => {
    	datatype => 'ARRAY[GetCharactersCharacterIdChatChannelsBlocked]',
    	base_name => 'blocked',
    	description => 'blocked array',
    	format => '',
    	read_only => '',
    		},
    'channel_id' => {
    	datatype => 'int',
    	base_name => 'channel_id',
    	description => 'Unique channel ID. Always negative for player-created channels. Permanent (CCP created) channels have a positive ID, but don&#39;t appear in the API',
    	format => '',
    	read_only => '',
    		},
    'comparison_key' => {
    	datatype => 'string',
    	base_name => 'comparison_key',
    	description => 'Normalized, unique string used to compare channel names',
    	format => '',
    	read_only => '',
    		},
    'has_password' => {
    	datatype => 'boolean',
    	base_name => 'has_password',
    	description => 'Whether this is a password protected channel',
    	format => '',
    	read_only => '',
    		},
    'motd' => {
    	datatype => 'string',
    	base_name => 'motd',
    	description => 'Message of the day for this channel',
    	format => '',
    	read_only => '',
    		},
    'muted' => {
    	datatype => 'ARRAY[GetCharactersCharacterIdChatChannelsMuted]',
    	base_name => 'muted',
    	description => 'muted array',
    	format => '',
    	read_only => '',
    		},
    'name' => {
    	datatype => 'string',
    	base_name => 'name',
    	description => 'Displayed name of channel',
    	format => '',
    	read_only => '',
    		},
    'operators' => {
    	datatype => 'ARRAY[GetCharactersCharacterIdChatChannelsOperator]',
    	base_name => 'operators',
    	description => 'operators array',
    	format => '',
    	read_only => '',
    		},
    'owner_id' => {
    	datatype => 'int',
    	base_name => 'owner_id',
    	description => 'owner_id integer',
    	format => '',
    	read_only => '',
    		},
});

__PACKAGE__->swagger_types( {
    'allowed' => 'ARRAY[GetCharactersCharacterIdChatChannelsAllowed]',
    'blocked' => 'ARRAY[GetCharactersCharacterIdChatChannelsBlocked]',
    'channel_id' => 'int',
    'comparison_key' => 'string',
    'has_password' => 'boolean',
    'motd' => 'string',
    'muted' => 'ARRAY[GetCharactersCharacterIdChatChannelsMuted]',
    'name' => 'string',
    'operators' => 'ARRAY[GetCharactersCharacterIdChatChannelsOperator]',
    'owner_id' => 'int'
} );

__PACKAGE__->attribute_map( {
    'allowed' => 'allowed',
    'blocked' => 'blocked',
    'channel_id' => 'channel_id',
    'comparison_key' => 'comparison_key',
    'has_password' => 'has_password',
    'motd' => 'motd',
    'muted' => 'muted',
    'name' => 'name',
    'operators' => 'operators',
    'owner_id' => 'owner_id'
} );

__PACKAGE__->mk_accessors(keys %{__PACKAGE__->attribute_map});


1;
