=begin comment

EVE Swagger Interface

An OpenAPI for EVE Online

OpenAPI spec version: 0.4.2.dev22

Generated by: https://github.com/swagger-api/swagger-codegen.git

=end comment

=cut

#
# NOTE: This class is auto generated by the swagger code generator program. 
# Do not edit the class manually.
# Ref: https://github.com/swagger-api/swagger-codegen
#
package EVE::ESI::Client::Object::GetCorporationsCorporationIdStructures200Ok;

require 5.6.0;
use strict;
use warnings;
use utf8;
use JSON qw(decode_json);
use Data::Dumper;
use Module::Runtime qw(use_module);
use Log::Any qw($log);
use Date::Parse;
use DateTime;

use base ("Class::Accessor", "Class::Data::Inheritable");


#
#200 ok object
#
# NOTE: This class is auto generated by the swagger code generator program. Do not edit the class manually.
# REF: https://github.com/swagger-api/swagger-codegen
#

=begin comment

EVE Swagger Interface

An OpenAPI for EVE Online

OpenAPI spec version: 0.4.2.dev22

Generated by: https://github.com/swagger-api/swagger-codegen.git

=end comment

=cut

#
# NOTE: This class is auto generated by the swagger code generator program. 
# Do not edit the class manually.
# Ref: https://github.com/swagger-api/swagger-codegen
#
__PACKAGE__->mk_classdata('attribute_map' => {});
__PACKAGE__->mk_classdata('swagger_types' => {});
__PACKAGE__->mk_classdata('method_documentation' => {}); 
__PACKAGE__->mk_classdata('class_documentation' => {});

# new object
sub new { 
    my ($class, %args) = @_; 

	my $self = bless {}, $class;
	
	foreach my $attribute (keys %{$class->attribute_map}) {
		my $args_key = $class->attribute_map->{$attribute};
		$self->$attribute( $args{ $args_key } );
	}
	
	return $self;
}  

# return perl hash
sub to_hash {
    return decode_json(JSON->new->convert_blessed->encode( shift ));
}

# used by JSON for serialization
sub TO_JSON { 
    my $self = shift;
    my $_data = {};
    foreach my $_key (keys %{$self->attribute_map}) {
        if (defined $self->{$_key}) {
            $_data->{$self->attribute_map->{$_key}} = $self->{$_key};
        }
    }
    return $_data;
}

# from Perl hashref
sub from_hash {
    my ($self, $hash) = @_;

    # loop through attributes and use swagger_types to deserialize the data
    while ( my ($_key, $_type) = each %{$self->swagger_types} ) {
    	my $_json_attribute = $self->attribute_map->{$_key}; 
        if ($_type =~ /^array\[/i) { # array
            my $_subclass = substr($_type, 6, -1);
            my @_array = ();
            foreach my $_element (@{$hash->{$_json_attribute}}) {
                push @_array, $self->_deserialize($_subclass, $_element);
            }
            $self->{$_key} = \@_array;
        } elsif (exists $hash->{$_json_attribute}) { #hash(model), primitive, datetime
            $self->{$_key} = $self->_deserialize($_type, $hash->{$_json_attribute});
        } else {
        	$log->debugf("Warning: %s (%s) does not exist in input hash\n", $_key, $_json_attribute);
        }
    }
  
    return $self;
}

# deserialize non-array data
sub _deserialize {
    my ($self, $type, $data) = @_;
    $log->debugf("deserializing %s with %s",Dumper($data), $type);
        
    if ($type eq 'DateTime') {
        return DateTime->from_epoch(epoch => str2time($data));
    } elsif ( grep( /^$type$/, ('int', 'double', 'string', 'boolean'))) {
        return $data;
    } else { # hash(model)
        my $_instance = eval "EVE::ESI::Client::Object::$type->new()";
        return $_instance->from_hash($data);
    }
}



__PACKAGE__->class_documentation({description => '200 ok object',
                                  class => 'GetCorporationsCorporationIdStructures200Ok',
                                  required => [], # TODO
}                                 );

__PACKAGE__->method_documentation({
    'corporation_id' => {
    	datatype => 'int',
    	base_name => 'corporation_id',
    	description => 'ID of the corporation that owns the structure',
    	format => '',
    	read_only => '',
    		},
    'current_vul' => {
    	datatype => 'ARRAY[GetCorporationsCorporationIdStructuresCurrentVul]',
    	base_name => 'current_vul',
    	description => 'This week&#39;s vulnerability windows, Monday is day 0',
    	format => '',
    	read_only => '',
    		},
    'fuel_expires' => {
    	datatype => 'DateTime',
    	base_name => 'fuel_expires',
    	description => 'Date on which the structure will run out of fuel',
    	format => '',
    	read_only => '',
    		},
    'next_vul' => {
    	datatype => 'ARRAY[GetCorporationsCorporationIdStructuresNextVul]',
    	base_name => 'next_vul',
    	description => 'Next week&#39;s vulnerability windows, Monday is day 0',
    	format => '',
    	read_only => '',
    		},
    'profile_id' => {
    	datatype => 'int',
    	base_name => 'profile_id',
    	description => 'The id of the ACL profile for this citadel',
    	format => '',
    	read_only => '',
    		},
    'services' => {
    	datatype => 'ARRAY[GetCorporationsCorporationIdStructuresService]',
    	base_name => 'services',
    	description => 'Contains a list of service upgrades, and their state',
    	format => '',
    	read_only => '',
    		},
    'state_timer_end' => {
    	datatype => 'DateTime',
    	base_name => 'state_timer_end',
    	description => 'Date at which the structure will move to it&#39;s next state',
    	format => '',
    	read_only => '',
    		},
    'state_timer_start' => {
    	datatype => 'DateTime',
    	base_name => 'state_timer_start',
    	description => 'Date at which the structure entered it&#39;s current state',
    	format => '',
    	read_only => '',
    		},
    'structure_id' => {
    	datatype => 'int',
    	base_name => 'structure_id',
    	description => 'The Item ID of the structure',
    	format => '',
    	read_only => '',
    		},
    'system_id' => {
    	datatype => 'int',
    	base_name => 'system_id',
    	description => 'The solar system the structure is in',
    	format => '',
    	read_only => '',
    		},
    'type_id' => {
    	datatype => 'int',
    	base_name => 'type_id',
    	description => 'The type id of the structure',
    	format => '',
    	read_only => '',
    		},
    'unanchors_at' => {
    	datatype => 'DateTime',
    	base_name => 'unanchors_at',
    	description => 'Date at which the structure will unanchor',
    	format => '',
    	read_only => '',
    		},
});

__PACKAGE__->swagger_types( {
    'corporation_id' => 'int',
    'current_vul' => 'ARRAY[GetCorporationsCorporationIdStructuresCurrentVul]',
    'fuel_expires' => 'DateTime',
    'next_vul' => 'ARRAY[GetCorporationsCorporationIdStructuresNextVul]',
    'profile_id' => 'int',
    'services' => 'ARRAY[GetCorporationsCorporationIdStructuresService]',
    'state_timer_end' => 'DateTime',
    'state_timer_start' => 'DateTime',
    'structure_id' => 'int',
    'system_id' => 'int',
    'type_id' => 'int',
    'unanchors_at' => 'DateTime'
} );

__PACKAGE__->attribute_map( {
    'corporation_id' => 'corporation_id',
    'current_vul' => 'current_vul',
    'fuel_expires' => 'fuel_expires',
    'next_vul' => 'next_vul',
    'profile_id' => 'profile_id',
    'services' => 'services',
    'state_timer_end' => 'state_timer_end',
    'state_timer_start' => 'state_timer_start',
    'structure_id' => 'structure_id',
    'system_id' => 'system_id',
    'type_id' => 'type_id',
    'unanchors_at' => 'unanchors_at'
} );

__PACKAGE__->mk_accessors(keys %{__PACKAGE__->attribute_map});


1;
