=begin comment

EVE Swagger Interface

An OpenAPI for EVE Online

OpenAPI spec version: 0.4.2.dev22

Generated by: https://github.com/swagger-api/swagger-codegen.git

=end comment

=cut

#
# NOTE: This class is auto generated by the swagger code generator program. 
# Do not edit the class manually.
# Ref: https://github.com/swagger-api/swagger-codegen
#
package EVE::ESI::Client::Object::GetDogmaAttributesAttributeIdOk;

require 5.6.0;
use strict;
use warnings;
use utf8;
use JSON qw(decode_json);
use Data::Dumper;
use Module::Runtime qw(use_module);
use Log::Any qw($log);
use Date::Parse;
use DateTime;

use base ("Class::Accessor", "Class::Data::Inheritable");


#
#200 ok object
#
# NOTE: This class is auto generated by the swagger code generator program. Do not edit the class manually.
# REF: https://github.com/swagger-api/swagger-codegen
#

=begin comment

EVE Swagger Interface

An OpenAPI for EVE Online

OpenAPI spec version: 0.4.2.dev22

Generated by: https://github.com/swagger-api/swagger-codegen.git

=end comment

=cut

#
# NOTE: This class is auto generated by the swagger code generator program. 
# Do not edit the class manually.
# Ref: https://github.com/swagger-api/swagger-codegen
#
__PACKAGE__->mk_classdata('attribute_map' => {});
__PACKAGE__->mk_classdata('swagger_types' => {});
__PACKAGE__->mk_classdata('method_documentation' => {}); 
__PACKAGE__->mk_classdata('class_documentation' => {});

# new object
sub new { 
    my ($class, %args) = @_; 

	my $self = bless {}, $class;
	
	foreach my $attribute (keys %{$class->attribute_map}) {
		my $args_key = $class->attribute_map->{$attribute};
		$self->$attribute( $args{ $args_key } );
	}
	
	return $self;
}  

# return perl hash
sub to_hash {
    return decode_json(JSON->new->convert_blessed->encode( shift ));
}

# used by JSON for serialization
sub TO_JSON { 
    my $self = shift;
    my $_data = {};
    foreach my $_key (keys %{$self->attribute_map}) {
        if (defined $self->{$_key}) {
            $_data->{$self->attribute_map->{$_key}} = $self->{$_key};
        }
    }
    return $_data;
}

# from Perl hashref
sub from_hash {
    my ($self, $hash) = @_;

    # loop through attributes and use swagger_types to deserialize the data
    while ( my ($_key, $_type) = each %{$self->swagger_types} ) {
    	my $_json_attribute = $self->attribute_map->{$_key}; 
        if ($_type =~ /^array\[/i) { # array
            my $_subclass = substr($_type, 6, -1);
            my @_array = ();
            foreach my $_element (@{$hash->{$_json_attribute}}) {
                push @_array, $self->_deserialize($_subclass, $_element);
            }
            $self->{$_key} = \@_array;
        } elsif (exists $hash->{$_json_attribute}) { #hash(model), primitive, datetime
            $self->{$_key} = $self->_deserialize($_type, $hash->{$_json_attribute});
        } else {
        	$log->debugf("Warning: %s (%s) does not exist in input hash\n", $_key, $_json_attribute);
        }
    }
  
    return $self;
}

# deserialize non-array data
sub _deserialize {
    my ($self, $type, $data) = @_;
    $log->debugf("deserializing %s with %s",Dumper($data), $type);
        
    if ($type eq 'DateTime') {
        return DateTime->from_epoch(epoch => str2time($data));
    } elsif ( grep( /^$type$/, ('int', 'double', 'string', 'boolean'))) {
        return $data;
    } else { # hash(model)
        my $_instance = eval "EVE::ESI::Client::Object::$type->new()";
        return $_instance->from_hash($data);
    }
}



__PACKAGE__->class_documentation({description => '200 ok object',
                                  class => 'GetDogmaAttributesAttributeIdOk',
                                  required => [], # TODO
}                                 );

__PACKAGE__->method_documentation({
    'attribute_id' => {
    	datatype => 'int',
    	base_name => 'attribute_id',
    	description => 'attribute_id integer',
    	format => '',
    	read_only => '',
    		},
    'default_value' => {
    	datatype => 'double',
    	base_name => 'default_value',
    	description => 'default_value number',
    	format => '',
    	read_only => '',
    		},
    'description' => {
    	datatype => 'string',
    	base_name => 'description',
    	description => 'description string',
    	format => '',
    	read_only => '',
    		},
    'display_name' => {
    	datatype => 'string',
    	base_name => 'display_name',
    	description => 'display_name string',
    	format => '',
    	read_only => '',
    		},
    'high_is_good' => {
    	datatype => 'boolean',
    	base_name => 'high_is_good',
    	description => 'high_is_good boolean',
    	format => '',
    	read_only => '',
    		},
    'icon_id' => {
    	datatype => 'int',
    	base_name => 'icon_id',
    	description => 'icon_id integer',
    	format => '',
    	read_only => '',
    		},
    'name' => {
    	datatype => 'string',
    	base_name => 'name',
    	description => 'name string',
    	format => '',
    	read_only => '',
    		},
    'published' => {
    	datatype => 'boolean',
    	base_name => 'published',
    	description => 'published boolean',
    	format => '',
    	read_only => '',
    		},
    'stackable' => {
    	datatype => 'boolean',
    	base_name => 'stackable',
    	description => 'stackable boolean',
    	format => '',
    	read_only => '',
    		},
    'unit_id' => {
    	datatype => 'int',
    	base_name => 'unit_id',
    	description => 'unit_id integer',
    	format => '',
    	read_only => '',
    		},
});

__PACKAGE__->swagger_types( {
    'attribute_id' => 'int',
    'default_value' => 'double',
    'description' => 'string',
    'display_name' => 'string',
    'high_is_good' => 'boolean',
    'icon_id' => 'int',
    'name' => 'string',
    'published' => 'boolean',
    'stackable' => 'boolean',
    'unit_id' => 'int'
} );

__PACKAGE__->attribute_map( {
    'attribute_id' => 'attribute_id',
    'default_value' => 'default_value',
    'description' => 'description',
    'display_name' => 'display_name',
    'high_is_good' => 'high_is_good',
    'icon_id' => 'icon_id',
    'name' => 'name',
    'published' => 'published',
    'stackable' => 'stackable',
    'unit_id' => 'unit_id'
} );

__PACKAGE__->mk_accessors(keys %{__PACKAGE__->attribute_map});


1;
