=begin comment

EVE Swagger Interface

An OpenAPI for EVE Online

OpenAPI spec version: 0.4.2.dev22

Generated by: https://github.com/swagger-api/swagger-codegen.git

=end comment

=cut

#
# NOTE: This class is auto generated by the swagger code generator program. 
# Do not edit the class manually.
# Ref: https://github.com/swagger-api/swagger-codegen
#
package EVE::ESI::Client::Object::GetSovereigntyCampaigns200Ok;

require 5.6.0;
use strict;
use warnings;
use utf8;
use JSON qw(decode_json);
use Data::Dumper;
use Module::Runtime qw(use_module);
use Log::Any qw($log);
use Date::Parse;
use DateTime;

use base ("Class::Accessor", "Class::Data::Inheritable");


#
#200 ok object
#
# NOTE: This class is auto generated by the swagger code generator program. Do not edit the class manually.
# REF: https://github.com/swagger-api/swagger-codegen
#

=begin comment

EVE Swagger Interface

An OpenAPI for EVE Online

OpenAPI spec version: 0.4.2.dev22

Generated by: https://github.com/swagger-api/swagger-codegen.git

=end comment

=cut

#
# NOTE: This class is auto generated by the swagger code generator program. 
# Do not edit the class manually.
# Ref: https://github.com/swagger-api/swagger-codegen
#
__PACKAGE__->mk_classdata('attribute_map' => {});
__PACKAGE__->mk_classdata('swagger_types' => {});
__PACKAGE__->mk_classdata('method_documentation' => {}); 
__PACKAGE__->mk_classdata('class_documentation' => {});

# new object
sub new { 
    my ($class, %args) = @_; 

	my $self = bless {}, $class;
	
	foreach my $attribute (keys %{$class->attribute_map}) {
		my $args_key = $class->attribute_map->{$attribute};
		$self->$attribute( $args{ $args_key } );
	}
	
	return $self;
}  

# return perl hash
sub to_hash {
    return decode_json(JSON->new->convert_blessed->encode( shift ));
}

# used by JSON for serialization
sub TO_JSON { 
    my $self = shift;
    my $_data = {};
    foreach my $_key (keys %{$self->attribute_map}) {
        if (defined $self->{$_key}) {
            $_data->{$self->attribute_map->{$_key}} = $self->{$_key};
        }
    }
    return $_data;
}

# from Perl hashref
sub from_hash {
    my ($self, $hash) = @_;

    # loop through attributes and use swagger_types to deserialize the data
    while ( my ($_key, $_type) = each %{$self->swagger_types} ) {
    	my $_json_attribute = $self->attribute_map->{$_key}; 
        if ($_type =~ /^array\[/i) { # array
            my $_subclass = substr($_type, 6, -1);
            my @_array = ();
            foreach my $_element (@{$hash->{$_json_attribute}}) {
                push @_array, $self->_deserialize($_subclass, $_element);
            }
            $self->{$_key} = \@_array;
        } elsif (exists $hash->{$_json_attribute}) { #hash(model), primitive, datetime
            $self->{$_key} = $self->_deserialize($_type, $hash->{$_json_attribute});
        } else {
        	$log->debugf("Warning: %s (%s) does not exist in input hash\n", $_key, $_json_attribute);
        }
    }
  
    return $self;
}

# deserialize non-array data
sub _deserialize {
    my ($self, $type, $data) = @_;
    $log->debugf("deserializing %s with %s",Dumper($data), $type);
        
    if ($type eq 'DateTime') {
        return DateTime->from_epoch(epoch => str2time($data));
    } elsif ( grep( /^$type$/, ('int', 'double', 'string', 'boolean'))) {
        return $data;
    } else { # hash(model)
        my $_instance = eval "EVE::ESI::Client::Object::$type->new()";
        return $_instance->from_hash($data);
    }
}



__PACKAGE__->class_documentation({description => '200 ok object',
                                  class => 'GetSovereigntyCampaigns200Ok',
                                  required => [], # TODO
}                                 );

__PACKAGE__->method_documentation({
    'attackers_score' => {
    	datatype => 'double',
    	base_name => 'attackers_score',
    	description => 'Score for all attacking parties, only present in Defense Events. ',
    	format => '',
    	read_only => '',
    		},
    'campaign_id' => {
    	datatype => 'int',
    	base_name => 'campaign_id',
    	description => 'Unique ID for this campaign.',
    	format => '',
    	read_only => '',
    		},
    'constellation_id' => {
    	datatype => 'int',
    	base_name => 'constellation_id',
    	description => 'The constellation in which the campaign will take place. ',
    	format => '',
    	read_only => '',
    		},
    'defender_id' => {
    	datatype => 'int',
    	base_name => 'defender_id',
    	description => 'Defending alliance, only present in Defense Events ',
    	format => '',
    	read_only => '',
    		},
    'defender_score' => {
    	datatype => 'double',
    	base_name => 'defender_score',
    	description => 'Score for the defending alliance, only present in Defense Events. ',
    	format => '',
    	read_only => '',
    		},
    'event_type' => {
    	datatype => 'string',
    	base_name => 'event_type',
    	description => 'Type of event this campaign is for. tcu_defense, ihub_defense and station_defense are referred to as \&quot;Defense Events\&quot;, station_freeport as \&quot;Freeport Events\&quot;. ',
    	format => '',
    	read_only => '',
    		},
    'participants' => {
    	datatype => 'ARRAY[GetSovereigntyCampaignsParticipant]',
    	base_name => 'participants',
    	description => 'Alliance participating and their respective scores, only present in Freeport Events. ',
    	format => '',
    	read_only => '',
    		},
    'solar_system_id' => {
    	datatype => 'int',
    	base_name => 'solar_system_id',
    	description => 'The solar system the structure is located in. ',
    	format => '',
    	read_only => '',
    		},
    'start_time' => {
    	datatype => 'DateTime',
    	base_name => 'start_time',
    	description => 'Time the event is scheduled to start. ',
    	format => '',
    	read_only => '',
    		},
    'structure_id' => {
    	datatype => 'int',
    	base_name => 'structure_id',
    	description => 'The structure item ID that is related to this campaign. ',
    	format => '',
    	read_only => '',
    		},
});

__PACKAGE__->swagger_types( {
    'attackers_score' => 'double',
    'campaign_id' => 'int',
    'constellation_id' => 'int',
    'defender_id' => 'int',
    'defender_score' => 'double',
    'event_type' => 'string',
    'participants' => 'ARRAY[GetSovereigntyCampaignsParticipant]',
    'solar_system_id' => 'int',
    'start_time' => 'DateTime',
    'structure_id' => 'int'
} );

__PACKAGE__->attribute_map( {
    'attackers_score' => 'attackers_score',
    'campaign_id' => 'campaign_id',
    'constellation_id' => 'constellation_id',
    'defender_id' => 'defender_id',
    'defender_score' => 'defender_score',
    'event_type' => 'event_type',
    'participants' => 'participants',
    'solar_system_id' => 'solar_system_id',
    'start_time' => 'start_time',
    'structure_id' => 'structure_id'
} );

__PACKAGE__->mk_accessors(keys %{__PACKAGE__->attribute_map});


1;
