=begin comment

EVE Swagger Interface

An OpenAPI for EVE Online

OpenAPI spec version: 0.4.2.dev22

Generated by: https://github.com/swagger-api/swagger-codegen.git

=end comment

=cut

#
# NOTE: This class is auto generated by the swagger code generator program. 
# Do not edit the class manually.
# Ref: https://github.com/swagger-api/swagger-codegen
#
package EVE::ESI::Client::ContactsApi;

require 5.6.0;
use strict;
use warnings;
use utf8; 
use Exporter;
use Carp qw( croak );
use Log::Any qw($log);

use EVE::ESI::Client::ApiClient;

use base "Class::Data::Inheritable";

__PACKAGE__->mk_classdata('method_documentation' => {});

sub new {
    my $class = shift;
    my $api_client;

    if ($_[0] && ref $_[0] && ref $_[0] eq 'EVE::ESI::Client::ApiClient' ) {
        $api_client = $_[0];
    } else {
        $api_client = EVE::ESI::Client::ApiClient->new(@_);
    }

    bless { api_client => $api_client }, $class;

}


#
# delete_characters_character_id_contacts
#
# Delete contacts
# 
# @param int $character_id ID for a character (required)
# @param ARRAY[int] $contact_ids A list of contacts to edit (required)
# @param string $datasource The server name you would like data from (optional, default to tranquility)
# @param string $token Access token to use, if preferred over a header (optional)
# @param string $user_agent Client identifier, takes precedence over headers (optional)
# @param string $x_user_agent Client identifier, takes precedence over User-Agent (optional)
{
    my $params = {
    'character_id' => {
        data_type => 'int',
        description => 'ID for a character',
        required => '1',
    },
    'contact_ids' => {
        data_type => 'ARRAY[int]',
        description => 'A list of contacts to edit',
        required => '1',
    },
    'datasource' => {
        data_type => 'string',
        description => 'The server name you would like data from',
        required => '0',
    },
    'token' => {
        data_type => 'string',
        description => 'Access token to use, if preferred over a header',
        required => '0',
    },
    'user_agent' => {
        data_type => 'string',
        description => 'Client identifier, takes precedence over headers',
        required => '0',
    },
    'x_user_agent' => {
        data_type => 'string',
        description => 'Client identifier, takes precedence over User-Agent',
        required => '0',
    },
    };
    __PACKAGE__->method_documentation->{ 'delete_characters_character_id_contacts' } = { 
    	summary => 'Delete contacts',
        params => $params,
        returns => undef,
        };
}
# @return void
#
sub delete_characters_character_id_contacts {
    my ($self, %args) = @_;

    # verify the required parameter 'character_id' is set
    unless (exists $args{'character_id'}) {
      croak("Missing the required parameter 'character_id' when calling delete_characters_character_id_contacts");
    }

    # verify the required parameter 'contact_ids' is set
    unless (exists $args{'contact_ids'}) {
      croak("Missing the required parameter 'contact_ids' when calling delete_characters_character_id_contacts");
    }

    # parse inputs
    my $_resource_path = '/characters/{character_id}/contacts/';

    my $_method = 'DELETE';
    my $query_params = {};
    my $header_params = {};
    my $form_params = {};

    # 'Accept' and 'Content-Type' header
    my $_header_accept = $self->{api_client}->select_header_accept('application/json');
    if ($_header_accept) {
        $header_params->{'Accept'} = $_header_accept;
    }
    $header_params->{'Content-Type'} = $self->{api_client}->select_header_content_type();

    # query params
    if ( exists $args{'datasource'}) {
        $query_params->{'datasource'} = $self->{api_client}->to_query_value($args{'datasource'});
    }

    # query params
    if ( exists $args{'token'}) {
        $query_params->{'token'} = $self->{api_client}->to_query_value($args{'token'});
    }

    # query params
    if ( exists $args{'user_agent'}) {
        $query_params->{'user_agent'} = $self->{api_client}->to_query_value($args{'user_agent'});
    }

    # header params
    if ( exists $args{'x_user_agent'}) {
        $header_params->{'X-User-Agent'} = $self->{api_client}->to_header_value($args{'x_user_agent'});
    }

    # path params
    if ( exists $args{'character_id'}) {
        my $_base_variable = "{" . "character_id" . "}";
        my $_base_value = $self->{api_client}->to_path_value($args{'character_id'});
        $_resource_path =~ s/$_base_variable/$_base_value/g;
    }

    my $_body_data;
    # body params
    if ( exists $args{'contact_ids'}) {
        $_body_data = $args{'contact_ids'};
    }

    # authentication setting, if any
    my $auth_settings = [qw(evesso )];

    # make the API Call
    $self->{api_client}->call_api($_resource_path, $_method,
                                           $query_params, $form_params,
                                           $header_params, $_body_data, $auth_settings);
    return;
}

#
# get_characters_character_id_contacts
#
# Get contacts
# 
# @param int $character_id ID for a character (required)
# @param string $datasource The server name you would like data from (optional, default to tranquility)
# @param int $page page integer (optional, default to 1)
# @param string $token Access token to use, if preferred over a header (optional)
# @param string $user_agent Client identifier, takes precedence over headers (optional)
# @param string $x_user_agent Client identifier, takes precedence over User-Agent (optional)
{
    my $params = {
    'character_id' => {
        data_type => 'int',
        description => 'ID for a character',
        required => '1',
    },
    'datasource' => {
        data_type => 'string',
        description => 'The server name you would like data from',
        required => '0',
    },
    'page' => {
        data_type => 'int',
        description => 'page integer',
        required => '0',
    },
    'token' => {
        data_type => 'string',
        description => 'Access token to use, if preferred over a header',
        required => '0',
    },
    'user_agent' => {
        data_type => 'string',
        description => 'Client identifier, takes precedence over headers',
        required => '0',
    },
    'x_user_agent' => {
        data_type => 'string',
        description => 'Client identifier, takes precedence over User-Agent',
        required => '0',
    },
    };
    __PACKAGE__->method_documentation->{ 'get_characters_character_id_contacts' } = { 
    	summary => 'Get contacts',
        params => $params,
        returns => 'ARRAY[GetCharactersCharacterIdContacts200Ok]',
        };
}
# @return ARRAY[GetCharactersCharacterIdContacts200Ok]
#
sub get_characters_character_id_contacts {
    my ($self, %args) = @_;

    # verify the required parameter 'character_id' is set
    unless (exists $args{'character_id'}) {
      croak("Missing the required parameter 'character_id' when calling get_characters_character_id_contacts");
    }

    # parse inputs
    my $_resource_path = '/characters/{character_id}/contacts/';

    my $_method = 'GET';
    my $query_params = {};
    my $header_params = {};
    my $form_params = {};

    # 'Accept' and 'Content-Type' header
    my $_header_accept = $self->{api_client}->select_header_accept('application/json');
    if ($_header_accept) {
        $header_params->{'Accept'} = $_header_accept;
    }
    $header_params->{'Content-Type'} = $self->{api_client}->select_header_content_type();

    # query params
    if ( exists $args{'datasource'}) {
        $query_params->{'datasource'} = $self->{api_client}->to_query_value($args{'datasource'});
    }

    # query params
    if ( exists $args{'page'}) {
        $query_params->{'page'} = $self->{api_client}->to_query_value($args{'page'});
    }

    # query params
    if ( exists $args{'token'}) {
        $query_params->{'token'} = $self->{api_client}->to_query_value($args{'token'});
    }

    # query params
    if ( exists $args{'user_agent'}) {
        $query_params->{'user_agent'} = $self->{api_client}->to_query_value($args{'user_agent'});
    }

    # header params
    if ( exists $args{'x_user_agent'}) {
        $header_params->{'X-User-Agent'} = $self->{api_client}->to_header_value($args{'x_user_agent'});
    }

    # path params
    if ( exists $args{'character_id'}) {
        my $_base_variable = "{" . "character_id" . "}";
        my $_base_value = $self->{api_client}->to_path_value($args{'character_id'});
        $_resource_path =~ s/$_base_variable/$_base_value/g;
    }

    my $_body_data;
    # authentication setting, if any
    my $auth_settings = [qw(evesso )];

    # make the API Call
    my $response = $self->{api_client}->call_api($_resource_path, $_method,
                                           $query_params, $form_params,
                                           $header_params, $_body_data, $auth_settings);
    if (!$response) {
        return;
    }
    my $_response_object = $self->{api_client}->deserialize('ARRAY[GetCharactersCharacterIdContacts200Ok]', $response);
    return $_response_object;
}

#
# get_characters_character_id_contacts_labels
#
# Get contact labels
# 
# @param int $character_id ID for a character (required)
# @param string $datasource The server name you would like data from (optional, default to tranquility)
# @param string $token Access token to use, if preferred over a header (optional)
# @param string $user_agent Client identifier, takes precedence over headers (optional)
# @param string $x_user_agent Client identifier, takes precedence over User-Agent (optional)
{
    my $params = {
    'character_id' => {
        data_type => 'int',
        description => 'ID for a character',
        required => '1',
    },
    'datasource' => {
        data_type => 'string',
        description => 'The server name you would like data from',
        required => '0',
    },
    'token' => {
        data_type => 'string',
        description => 'Access token to use, if preferred over a header',
        required => '0',
    },
    'user_agent' => {
        data_type => 'string',
        description => 'Client identifier, takes precedence over headers',
        required => '0',
    },
    'x_user_agent' => {
        data_type => 'string',
        description => 'Client identifier, takes precedence over User-Agent',
        required => '0',
    },
    };
    __PACKAGE__->method_documentation->{ 'get_characters_character_id_contacts_labels' } = { 
    	summary => 'Get contact labels',
        params => $params,
        returns => 'ARRAY[GetCharactersCharacterIdContactsLabels200Ok]',
        };
}
# @return ARRAY[GetCharactersCharacterIdContactsLabels200Ok]
#
sub get_characters_character_id_contacts_labels {
    my ($self, %args) = @_;

    # verify the required parameter 'character_id' is set
    unless (exists $args{'character_id'}) {
      croak("Missing the required parameter 'character_id' when calling get_characters_character_id_contacts_labels");
    }

    # parse inputs
    my $_resource_path = '/characters/{character_id}/contacts/labels/';

    my $_method = 'GET';
    my $query_params = {};
    my $header_params = {};
    my $form_params = {};

    # 'Accept' and 'Content-Type' header
    my $_header_accept = $self->{api_client}->select_header_accept('application/json');
    if ($_header_accept) {
        $header_params->{'Accept'} = $_header_accept;
    }
    $header_params->{'Content-Type'} = $self->{api_client}->select_header_content_type();

    # query params
    if ( exists $args{'datasource'}) {
        $query_params->{'datasource'} = $self->{api_client}->to_query_value($args{'datasource'});
    }

    # query params
    if ( exists $args{'token'}) {
        $query_params->{'token'} = $self->{api_client}->to_query_value($args{'token'});
    }

    # query params
    if ( exists $args{'user_agent'}) {
        $query_params->{'user_agent'} = $self->{api_client}->to_query_value($args{'user_agent'});
    }

    # header params
    if ( exists $args{'x_user_agent'}) {
        $header_params->{'X-User-Agent'} = $self->{api_client}->to_header_value($args{'x_user_agent'});
    }

    # path params
    if ( exists $args{'character_id'}) {
        my $_base_variable = "{" . "character_id" . "}";
        my $_base_value = $self->{api_client}->to_path_value($args{'character_id'});
        $_resource_path =~ s/$_base_variable/$_base_value/g;
    }

    my $_body_data;
    # authentication setting, if any
    my $auth_settings = [qw(evesso )];

    # make the API Call
    my $response = $self->{api_client}->call_api($_resource_path, $_method,
                                           $query_params, $form_params,
                                           $header_params, $_body_data, $auth_settings);
    if (!$response) {
        return;
    }
    my $_response_object = $self->{api_client}->deserialize('ARRAY[GetCharactersCharacterIdContactsLabels200Ok]', $response);
    return $_response_object;
}

#
# post_characters_character_id_contacts
#
# Add contacts
# 
# @param int $character_id ID for a character (required)
# @param ARRAY[int] $contact_ids A list of contacts to add (required)
# @param double $standing Standing for the new contact (required)
# @param string $datasource The server name you would like data from (optional, default to tranquility)
# @param int $label_id Add a custom label to the new contact (optional, default to 0)
# @param string $token Access token to use, if preferred over a header (optional)
# @param string $user_agent Client identifier, takes precedence over headers (optional)
# @param boolean $watched Whether the new contact should be watched, note this is only effective on characters (optional, default to false)
# @param string $x_user_agent Client identifier, takes precedence over User-Agent (optional)
{
    my $params = {
    'character_id' => {
        data_type => 'int',
        description => 'ID for a character',
        required => '1',
    },
    'contact_ids' => {
        data_type => 'ARRAY[int]',
        description => 'A list of contacts to add',
        required => '1',
    },
    'standing' => {
        data_type => 'double',
        description => 'Standing for the new contact',
        required => '1',
    },
    'datasource' => {
        data_type => 'string',
        description => 'The server name you would like data from',
        required => '0',
    },
    'label_id' => {
        data_type => 'int',
        description => 'Add a custom label to the new contact',
        required => '0',
    },
    'token' => {
        data_type => 'string',
        description => 'Access token to use, if preferred over a header',
        required => '0',
    },
    'user_agent' => {
        data_type => 'string',
        description => 'Client identifier, takes precedence over headers',
        required => '0',
    },
    'watched' => {
        data_type => 'boolean',
        description => 'Whether the new contact should be watched, note this is only effective on characters',
        required => '0',
    },
    'x_user_agent' => {
        data_type => 'string',
        description => 'Client identifier, takes precedence over User-Agent',
        required => '0',
    },
    };
    __PACKAGE__->method_documentation->{ 'post_characters_character_id_contacts' } = { 
    	summary => 'Add contacts',
        params => $params,
        returns => 'ARRAY[int]',
        };
}
# @return ARRAY[int]
#
sub post_characters_character_id_contacts {
    my ($self, %args) = @_;

    # verify the required parameter 'character_id' is set
    unless (exists $args{'character_id'}) {
      croak("Missing the required parameter 'character_id' when calling post_characters_character_id_contacts");
    }

    # verify the required parameter 'contact_ids' is set
    unless (exists $args{'contact_ids'}) {
      croak("Missing the required parameter 'contact_ids' when calling post_characters_character_id_contacts");
    }

    # verify the required parameter 'standing' is set
    unless (exists $args{'standing'}) {
      croak("Missing the required parameter 'standing' when calling post_characters_character_id_contacts");
    }

    # parse inputs
    my $_resource_path = '/characters/{character_id}/contacts/';

    my $_method = 'POST';
    my $query_params = {};
    my $header_params = {};
    my $form_params = {};

    # 'Accept' and 'Content-Type' header
    my $_header_accept = $self->{api_client}->select_header_accept('application/json');
    if ($_header_accept) {
        $header_params->{'Accept'} = $_header_accept;
    }
    $header_params->{'Content-Type'} = $self->{api_client}->select_header_content_type();

    # query params
    if ( exists $args{'datasource'}) {
        $query_params->{'datasource'} = $self->{api_client}->to_query_value($args{'datasource'});
    }

    # query params
    if ( exists $args{'label_id'}) {
        $query_params->{'label_id'} = $self->{api_client}->to_query_value($args{'label_id'});
    }

    # query params
    if ( exists $args{'standing'}) {
        $query_params->{'standing'} = $self->{api_client}->to_query_value($args{'standing'});
    }

    # query params
    if ( exists $args{'token'}) {
        $query_params->{'token'} = $self->{api_client}->to_query_value($args{'token'});
    }

    # query params
    if ( exists $args{'user_agent'}) {
        $query_params->{'user_agent'} = $self->{api_client}->to_query_value($args{'user_agent'});
    }

    # query params
    if ( exists $args{'watched'}) {
        $query_params->{'watched'} = $self->{api_client}->to_query_value($args{'watched'});
    }

    # header params
    if ( exists $args{'x_user_agent'}) {
        $header_params->{'X-User-Agent'} = $self->{api_client}->to_header_value($args{'x_user_agent'});
    }

    # path params
    if ( exists $args{'character_id'}) {
        my $_base_variable = "{" . "character_id" . "}";
        my $_base_value = $self->{api_client}->to_path_value($args{'character_id'});
        $_resource_path =~ s/$_base_variable/$_base_value/g;
    }

    my $_body_data;
    # body params
    if ( exists $args{'contact_ids'}) {
        $_body_data = $args{'contact_ids'};
    }

    # authentication setting, if any
    my $auth_settings = [qw(evesso )];

    # make the API Call
    my $response = $self->{api_client}->call_api($_resource_path, $_method,
                                           $query_params, $form_params,
                                           $header_params, $_body_data, $auth_settings);
    if (!$response) {
        return;
    }
    my $_response_object = $self->{api_client}->deserialize('ARRAY[int]', $response);
    return $_response_object;
}

#
# put_characters_character_id_contacts
#
# Edit contacts
# 
# @param int $character_id ID for a character (required)
# @param ARRAY[int] $contact_ids A list of contacts to edit (required)
# @param double $standing Standing for the contact (required)
# @param string $datasource The server name you would like data from (optional, default to tranquility)
# @param int $label_id Add a custom label to the contact, use 0 for clearing label (optional, default to 0)
# @param string $token Access token to use, if preferred over a header (optional)
# @param string $user_agent Client identifier, takes precedence over headers (optional)
# @param boolean $watched Whether the contact should be watched, note this is only effective on characters (optional, default to false)
# @param string $x_user_agent Client identifier, takes precedence over User-Agent (optional)
{
    my $params = {
    'character_id' => {
        data_type => 'int',
        description => 'ID for a character',
        required => '1',
    },
    'contact_ids' => {
        data_type => 'ARRAY[int]',
        description => 'A list of contacts to edit',
        required => '1',
    },
    'standing' => {
        data_type => 'double',
        description => 'Standing for the contact',
        required => '1',
    },
    'datasource' => {
        data_type => 'string',
        description => 'The server name you would like data from',
        required => '0',
    },
    'label_id' => {
        data_type => 'int',
        description => 'Add a custom label to the contact, use 0 for clearing label',
        required => '0',
    },
    'token' => {
        data_type => 'string',
        description => 'Access token to use, if preferred over a header',
        required => '0',
    },
    'user_agent' => {
        data_type => 'string',
        description => 'Client identifier, takes precedence over headers',
        required => '0',
    },
    'watched' => {
        data_type => 'boolean',
        description => 'Whether the contact should be watched, note this is only effective on characters',
        required => '0',
    },
    'x_user_agent' => {
        data_type => 'string',
        description => 'Client identifier, takes precedence over User-Agent',
        required => '0',
    },
    };
    __PACKAGE__->method_documentation->{ 'put_characters_character_id_contacts' } = { 
    	summary => 'Edit contacts',
        params => $params,
        returns => undef,
        };
}
# @return void
#
sub put_characters_character_id_contacts {
    my ($self, %args) = @_;

    # verify the required parameter 'character_id' is set
    unless (exists $args{'character_id'}) {
      croak("Missing the required parameter 'character_id' when calling put_characters_character_id_contacts");
    }

    # verify the required parameter 'contact_ids' is set
    unless (exists $args{'contact_ids'}) {
      croak("Missing the required parameter 'contact_ids' when calling put_characters_character_id_contacts");
    }

    # verify the required parameter 'standing' is set
    unless (exists $args{'standing'}) {
      croak("Missing the required parameter 'standing' when calling put_characters_character_id_contacts");
    }

    # parse inputs
    my $_resource_path = '/characters/{character_id}/contacts/';

    my $_method = 'PUT';
    my $query_params = {};
    my $header_params = {};
    my $form_params = {};

    # 'Accept' and 'Content-Type' header
    my $_header_accept = $self->{api_client}->select_header_accept('application/json');
    if ($_header_accept) {
        $header_params->{'Accept'} = $_header_accept;
    }
    $header_params->{'Content-Type'} = $self->{api_client}->select_header_content_type();

    # query params
    if ( exists $args{'datasource'}) {
        $query_params->{'datasource'} = $self->{api_client}->to_query_value($args{'datasource'});
    }

    # query params
    if ( exists $args{'label_id'}) {
        $query_params->{'label_id'} = $self->{api_client}->to_query_value($args{'label_id'});
    }

    # query params
    if ( exists $args{'standing'}) {
        $query_params->{'standing'} = $self->{api_client}->to_query_value($args{'standing'});
    }

    # query params
    if ( exists $args{'token'}) {
        $query_params->{'token'} = $self->{api_client}->to_query_value($args{'token'});
    }

    # query params
    if ( exists $args{'user_agent'}) {
        $query_params->{'user_agent'} = $self->{api_client}->to_query_value($args{'user_agent'});
    }

    # query params
    if ( exists $args{'watched'}) {
        $query_params->{'watched'} = $self->{api_client}->to_query_value($args{'watched'});
    }

    # header params
    if ( exists $args{'x_user_agent'}) {
        $header_params->{'X-User-Agent'} = $self->{api_client}->to_header_value($args{'x_user_agent'});
    }

    # path params
    if ( exists $args{'character_id'}) {
        my $_base_variable = "{" . "character_id" . "}";
        my $_base_value = $self->{api_client}->to_path_value($args{'character_id'});
        $_resource_path =~ s/$_base_variable/$_base_value/g;
    }

    my $_body_data;
    # body params
    if ( exists $args{'contact_ids'}) {
        $_body_data = $args{'contact_ids'};
    }

    # authentication setting, if any
    my $auth_settings = [qw(evesso )];

    # make the API Call
    $self->{api_client}->call_api($_resource_path, $_method,
                                           $query_params, $form_params,
                                           $header_params, $_body_data, $auth_settings);
    return;
}

1;
