=begin comment

EVE Swagger Interface

An OpenAPI for EVE Online

OpenAPI spec version: 0.4.2.dev22

Generated by: https://github.com/swagger-api/swagger-codegen.git

=end comment

=cut

#
# NOTE: This class is auto generated by the swagger code generator program. 
# Do not edit the class manually.
# Ref: https://github.com/swagger-api/swagger-codegen
#
package EVE::ESI::Client::CorporationApi;

require 5.6.0;
use strict;
use warnings;
use utf8; 
use Exporter;
use Carp qw( croak );
use Log::Any qw($log);

use EVE::ESI::Client::ApiClient;

use base "Class::Data::Inheritable";

__PACKAGE__->mk_classdata('method_documentation' => {});

sub new {
    my $class = shift;
    my $api_client;

    if ($_[0] && ref $_[0] && ref $_[0] eq 'EVE::ESI::Client::ApiClient' ) {
        $api_client = $_[0];
    } else {
        $api_client = EVE::ESI::Client::ApiClient->new(@_);
    }

    bless { api_client => $api_client }, $class;

}


#
# get_corporations_corporation_id
#
# Get corporation information
# 
# @param int $corporation_id An Eve corporation ID (required)
# @param string $datasource The server name you would like data from (optional, default to tranquility)
# @param string $user_agent Client identifier, takes precedence over headers (optional)
# @param string $x_user_agent Client identifier, takes precedence over User-Agent (optional)
{
    my $params = {
    'corporation_id' => {
        data_type => 'int',
        description => 'An Eve corporation ID',
        required => '1',
    },
    'datasource' => {
        data_type => 'string',
        description => 'The server name you would like data from',
        required => '0',
    },
    'user_agent' => {
        data_type => 'string',
        description => 'Client identifier, takes precedence over headers',
        required => '0',
    },
    'x_user_agent' => {
        data_type => 'string',
        description => 'Client identifier, takes precedence over User-Agent',
        required => '0',
    },
    };
    __PACKAGE__->method_documentation->{ 'get_corporations_corporation_id' } = { 
    	summary => 'Get corporation information',
        params => $params,
        returns => 'GetCorporationsCorporationIdOk',
        };
}
# @return GetCorporationsCorporationIdOk
#
sub get_corporations_corporation_id {
    my ($self, %args) = @_;

    # verify the required parameter 'corporation_id' is set
    unless (exists $args{'corporation_id'}) {
      croak("Missing the required parameter 'corporation_id' when calling get_corporations_corporation_id");
    }

    # parse inputs
    my $_resource_path = '/corporations/{corporation_id}/';

    my $_method = 'GET';
    my $query_params = {};
    my $header_params = {};
    my $form_params = {};

    # 'Accept' and 'Content-Type' header
    my $_header_accept = $self->{api_client}->select_header_accept('application/json');
    if ($_header_accept) {
        $header_params->{'Accept'} = $_header_accept;
    }
    $header_params->{'Content-Type'} = $self->{api_client}->select_header_content_type();

    # query params
    if ( exists $args{'datasource'}) {
        $query_params->{'datasource'} = $self->{api_client}->to_query_value($args{'datasource'});
    }

    # query params
    if ( exists $args{'user_agent'}) {
        $query_params->{'user_agent'} = $self->{api_client}->to_query_value($args{'user_agent'});
    }

    # header params
    if ( exists $args{'x_user_agent'}) {
        $header_params->{'X-User-Agent'} = $self->{api_client}->to_header_value($args{'x_user_agent'});
    }

    # path params
    if ( exists $args{'corporation_id'}) {
        my $_base_variable = "{" . "corporation_id" . "}";
        my $_base_value = $self->{api_client}->to_path_value($args{'corporation_id'});
        $_resource_path =~ s/$_base_variable/$_base_value/g;
    }

    my $_body_data;
    # authentication setting, if any
    my $auth_settings = [qw()];

    # make the API Call
    my $response = $self->{api_client}->call_api($_resource_path, $_method,
                                           $query_params, $form_params,
                                           $header_params, $_body_data, $auth_settings);
    if (!$response) {
        return;
    }
    my $_response_object = $self->{api_client}->deserialize('GetCorporationsCorporationIdOk', $response);
    return $_response_object;
}

#
# get_corporations_corporation_id_alliancehistory
#
# Get alliance history
# 
# @param int $corporation_id An EVE corporation ID (required)
# @param string $datasource The server name you would like data from (optional, default to tranquility)
# @param string $user_agent Client identifier, takes precedence over headers (optional)
# @param string $x_user_agent Client identifier, takes precedence over User-Agent (optional)
{
    my $params = {
    'corporation_id' => {
        data_type => 'int',
        description => 'An EVE corporation ID',
        required => '1',
    },
    'datasource' => {
        data_type => 'string',
        description => 'The server name you would like data from',
        required => '0',
    },
    'user_agent' => {
        data_type => 'string',
        description => 'Client identifier, takes precedence over headers',
        required => '0',
    },
    'x_user_agent' => {
        data_type => 'string',
        description => 'Client identifier, takes precedence over User-Agent',
        required => '0',
    },
    };
    __PACKAGE__->method_documentation->{ 'get_corporations_corporation_id_alliancehistory' } = { 
    	summary => 'Get alliance history',
        params => $params,
        returns => 'ARRAY[GetCorporationsCorporationIdAlliancehistory200Ok]',
        };
}
# @return ARRAY[GetCorporationsCorporationIdAlliancehistory200Ok]
#
sub get_corporations_corporation_id_alliancehistory {
    my ($self, %args) = @_;

    # verify the required parameter 'corporation_id' is set
    unless (exists $args{'corporation_id'}) {
      croak("Missing the required parameter 'corporation_id' when calling get_corporations_corporation_id_alliancehistory");
    }

    # parse inputs
    my $_resource_path = '/corporations/{corporation_id}/alliancehistory/';

    my $_method = 'GET';
    my $query_params = {};
    my $header_params = {};
    my $form_params = {};

    # 'Accept' and 'Content-Type' header
    my $_header_accept = $self->{api_client}->select_header_accept('application/json');
    if ($_header_accept) {
        $header_params->{'Accept'} = $_header_accept;
    }
    $header_params->{'Content-Type'} = $self->{api_client}->select_header_content_type();

    # query params
    if ( exists $args{'datasource'}) {
        $query_params->{'datasource'} = $self->{api_client}->to_query_value($args{'datasource'});
    }

    # query params
    if ( exists $args{'user_agent'}) {
        $query_params->{'user_agent'} = $self->{api_client}->to_query_value($args{'user_agent'});
    }

    # header params
    if ( exists $args{'x_user_agent'}) {
        $header_params->{'X-User-Agent'} = $self->{api_client}->to_header_value($args{'x_user_agent'});
    }

    # path params
    if ( exists $args{'corporation_id'}) {
        my $_base_variable = "{" . "corporation_id" . "}";
        my $_base_value = $self->{api_client}->to_path_value($args{'corporation_id'});
        $_resource_path =~ s/$_base_variable/$_base_value/g;
    }

    my $_body_data;
    # authentication setting, if any
    my $auth_settings = [qw()];

    # make the API Call
    my $response = $self->{api_client}->call_api($_resource_path, $_method,
                                           $query_params, $form_params,
                                           $header_params, $_body_data, $auth_settings);
    if (!$response) {
        return;
    }
    my $_response_object = $self->{api_client}->deserialize('ARRAY[GetCorporationsCorporationIdAlliancehistory200Ok]', $response);
    return $_response_object;
}

#
# get_corporations_corporation_id_icons
#
# Get corporation icon
# 
# @param int $corporation_id An EVE corporation ID (required)
# @param string $datasource The server name you would like data from (optional, default to tranquility)
# @param string $user_agent Client identifier, takes precedence over headers (optional)
# @param string $x_user_agent Client identifier, takes precedence over User-Agent (optional)
{
    my $params = {
    'corporation_id' => {
        data_type => 'int',
        description => 'An EVE corporation ID',
        required => '1',
    },
    'datasource' => {
        data_type => 'string',
        description => 'The server name you would like data from',
        required => '0',
    },
    'user_agent' => {
        data_type => 'string',
        description => 'Client identifier, takes precedence over headers',
        required => '0',
    },
    'x_user_agent' => {
        data_type => 'string',
        description => 'Client identifier, takes precedence over User-Agent',
        required => '0',
    },
    };
    __PACKAGE__->method_documentation->{ 'get_corporations_corporation_id_icons' } = { 
    	summary => 'Get corporation icon',
        params => $params,
        returns => 'GetCorporationsCorporationIdIconsOk',
        };
}
# @return GetCorporationsCorporationIdIconsOk
#
sub get_corporations_corporation_id_icons {
    my ($self, %args) = @_;

    # verify the required parameter 'corporation_id' is set
    unless (exists $args{'corporation_id'}) {
      croak("Missing the required parameter 'corporation_id' when calling get_corporations_corporation_id_icons");
    }

    # parse inputs
    my $_resource_path = '/corporations/{corporation_id}/icons/';

    my $_method = 'GET';
    my $query_params = {};
    my $header_params = {};
    my $form_params = {};

    # 'Accept' and 'Content-Type' header
    my $_header_accept = $self->{api_client}->select_header_accept('application/json');
    if ($_header_accept) {
        $header_params->{'Accept'} = $_header_accept;
    }
    $header_params->{'Content-Type'} = $self->{api_client}->select_header_content_type();

    # query params
    if ( exists $args{'datasource'}) {
        $query_params->{'datasource'} = $self->{api_client}->to_query_value($args{'datasource'});
    }

    # query params
    if ( exists $args{'user_agent'}) {
        $query_params->{'user_agent'} = $self->{api_client}->to_query_value($args{'user_agent'});
    }

    # header params
    if ( exists $args{'x_user_agent'}) {
        $header_params->{'X-User-Agent'} = $self->{api_client}->to_header_value($args{'x_user_agent'});
    }

    # path params
    if ( exists $args{'corporation_id'}) {
        my $_base_variable = "{" . "corporation_id" . "}";
        my $_base_value = $self->{api_client}->to_path_value($args{'corporation_id'});
        $_resource_path =~ s/$_base_variable/$_base_value/g;
    }

    my $_body_data;
    # authentication setting, if any
    my $auth_settings = [qw()];

    # make the API Call
    my $response = $self->{api_client}->call_api($_resource_path, $_method,
                                           $query_params, $form_params,
                                           $header_params, $_body_data, $auth_settings);
    if (!$response) {
        return;
    }
    my $_response_object = $self->{api_client}->deserialize('GetCorporationsCorporationIdIconsOk', $response);
    return $_response_object;
}

#
# get_corporations_corporation_id_members
#
# Get corporation members
# 
# @param int $corporation_id A corporation ID (required)
# @param string $datasource The server name you would like data from (optional, default to tranquility)
# @param string $token Access token to use, if preferred over a header (optional)
# @param string $user_agent Client identifier, takes precedence over headers (optional)
# @param string $x_user_agent Client identifier, takes precedence over User-Agent (optional)
{
    my $params = {
    'corporation_id' => {
        data_type => 'int',
        description => 'A corporation ID',
        required => '1',
    },
    'datasource' => {
        data_type => 'string',
        description => 'The server name you would like data from',
        required => '0',
    },
    'token' => {
        data_type => 'string',
        description => 'Access token to use, if preferred over a header',
        required => '0',
    },
    'user_agent' => {
        data_type => 'string',
        description => 'Client identifier, takes precedence over headers',
        required => '0',
    },
    'x_user_agent' => {
        data_type => 'string',
        description => 'Client identifier, takes precedence over User-Agent',
        required => '0',
    },
    };
    __PACKAGE__->method_documentation->{ 'get_corporations_corporation_id_members' } = { 
    	summary => 'Get corporation members',
        params => $params,
        returns => 'ARRAY[GetCorporationsCorporationIdMembers200Ok]',
        };
}
# @return ARRAY[GetCorporationsCorporationIdMembers200Ok]
#
sub get_corporations_corporation_id_members {
    my ($self, %args) = @_;

    # verify the required parameter 'corporation_id' is set
    unless (exists $args{'corporation_id'}) {
      croak("Missing the required parameter 'corporation_id' when calling get_corporations_corporation_id_members");
    }

    # parse inputs
    my $_resource_path = '/corporations/{corporation_id}/members/';

    my $_method = 'GET';
    my $query_params = {};
    my $header_params = {};
    my $form_params = {};

    # 'Accept' and 'Content-Type' header
    my $_header_accept = $self->{api_client}->select_header_accept('application/json');
    if ($_header_accept) {
        $header_params->{'Accept'} = $_header_accept;
    }
    $header_params->{'Content-Type'} = $self->{api_client}->select_header_content_type();

    # query params
    if ( exists $args{'datasource'}) {
        $query_params->{'datasource'} = $self->{api_client}->to_query_value($args{'datasource'});
    }

    # query params
    if ( exists $args{'token'}) {
        $query_params->{'token'} = $self->{api_client}->to_query_value($args{'token'});
    }

    # query params
    if ( exists $args{'user_agent'}) {
        $query_params->{'user_agent'} = $self->{api_client}->to_query_value($args{'user_agent'});
    }

    # header params
    if ( exists $args{'x_user_agent'}) {
        $header_params->{'X-User-Agent'} = $self->{api_client}->to_header_value($args{'x_user_agent'});
    }

    # path params
    if ( exists $args{'corporation_id'}) {
        my $_base_variable = "{" . "corporation_id" . "}";
        my $_base_value = $self->{api_client}->to_path_value($args{'corporation_id'});
        $_resource_path =~ s/$_base_variable/$_base_value/g;
    }

    my $_body_data;
    # authentication setting, if any
    my $auth_settings = [qw(evesso )];

    # make the API Call
    my $response = $self->{api_client}->call_api($_resource_path, $_method,
                                           $query_params, $form_params,
                                           $header_params, $_body_data, $auth_settings);
    if (!$response) {
        return;
    }
    my $_response_object = $self->{api_client}->deserialize('ARRAY[GetCorporationsCorporationIdMembers200Ok]', $response);
    return $_response_object;
}

#
# get_corporations_corporation_id_roles
#
# Get corporation member roles
# 
# @param int $corporation_id A corporation ID (required)
# @param string $datasource The server name you would like data from (optional, default to tranquility)
# @param string $token Access token to use, if preferred over a header (optional)
# @param string $user_agent Client identifier, takes precedence over headers (optional)
# @param string $x_user_agent Client identifier, takes precedence over User-Agent (optional)
{
    my $params = {
    'corporation_id' => {
        data_type => 'int',
        description => 'A corporation ID',
        required => '1',
    },
    'datasource' => {
        data_type => 'string',
        description => 'The server name you would like data from',
        required => '0',
    },
    'token' => {
        data_type => 'string',
        description => 'Access token to use, if preferred over a header',
        required => '0',
    },
    'user_agent' => {
        data_type => 'string',
        description => 'Client identifier, takes precedence over headers',
        required => '0',
    },
    'x_user_agent' => {
        data_type => 'string',
        description => 'Client identifier, takes precedence over User-Agent',
        required => '0',
    },
    };
    __PACKAGE__->method_documentation->{ 'get_corporations_corporation_id_roles' } = { 
    	summary => 'Get corporation member roles',
        params => $params,
        returns => 'ARRAY[GetCorporationsCorporationIdRoles200Ok]',
        };
}
# @return ARRAY[GetCorporationsCorporationIdRoles200Ok]
#
sub get_corporations_corporation_id_roles {
    my ($self, %args) = @_;

    # verify the required parameter 'corporation_id' is set
    unless (exists $args{'corporation_id'}) {
      croak("Missing the required parameter 'corporation_id' when calling get_corporations_corporation_id_roles");
    }

    # parse inputs
    my $_resource_path = '/corporations/{corporation_id}/roles/';

    my $_method = 'GET';
    my $query_params = {};
    my $header_params = {};
    my $form_params = {};

    # 'Accept' and 'Content-Type' header
    my $_header_accept = $self->{api_client}->select_header_accept('application/json');
    if ($_header_accept) {
        $header_params->{'Accept'} = $_header_accept;
    }
    $header_params->{'Content-Type'} = $self->{api_client}->select_header_content_type();

    # query params
    if ( exists $args{'datasource'}) {
        $query_params->{'datasource'} = $self->{api_client}->to_query_value($args{'datasource'});
    }

    # query params
    if ( exists $args{'token'}) {
        $query_params->{'token'} = $self->{api_client}->to_query_value($args{'token'});
    }

    # query params
    if ( exists $args{'user_agent'}) {
        $query_params->{'user_agent'} = $self->{api_client}->to_query_value($args{'user_agent'});
    }

    # header params
    if ( exists $args{'x_user_agent'}) {
        $header_params->{'X-User-Agent'} = $self->{api_client}->to_header_value($args{'x_user_agent'});
    }

    # path params
    if ( exists $args{'corporation_id'}) {
        my $_base_variable = "{" . "corporation_id" . "}";
        my $_base_value = $self->{api_client}->to_path_value($args{'corporation_id'});
        $_resource_path =~ s/$_base_variable/$_base_value/g;
    }

    my $_body_data;
    # authentication setting, if any
    my $auth_settings = [qw(evesso )];

    # make the API Call
    my $response = $self->{api_client}->call_api($_resource_path, $_method,
                                           $query_params, $form_params,
                                           $header_params, $_body_data, $auth_settings);
    if (!$response) {
        return;
    }
    my $_response_object = $self->{api_client}->deserialize('ARRAY[GetCorporationsCorporationIdRoles200Ok]', $response);
    return $_response_object;
}

#
# get_corporations_corporation_id_structures
#
# Get corporation structures
# 
# @param int $corporation_id A corporation ID (required)
# @param string $datasource The server name you would like data from (optional, default to tranquility)
# @param string $language Language to use in the response (optional, default to en-us)
# @param int $page Which page to query, 250 structures per page (optional)
# @param string $token Access token to use, if preferred over a header (optional)
# @param string $user_agent Client identifier, takes precedence over headers (optional)
# @param string $x_user_agent Client identifier, takes precedence over User-Agent (optional)
{
    my $params = {
    'corporation_id' => {
        data_type => 'int',
        description => 'A corporation ID',
        required => '1',
    },
    'datasource' => {
        data_type => 'string',
        description => 'The server name you would like data from',
        required => '0',
    },
    'language' => {
        data_type => 'string',
        description => 'Language to use in the response',
        required => '0',
    },
    'page' => {
        data_type => 'int',
        description => 'Which page to query, 250 structures per page',
        required => '0',
    },
    'token' => {
        data_type => 'string',
        description => 'Access token to use, if preferred over a header',
        required => '0',
    },
    'user_agent' => {
        data_type => 'string',
        description => 'Client identifier, takes precedence over headers',
        required => '0',
    },
    'x_user_agent' => {
        data_type => 'string',
        description => 'Client identifier, takes precedence over User-Agent',
        required => '0',
    },
    };
    __PACKAGE__->method_documentation->{ 'get_corporations_corporation_id_structures' } = { 
    	summary => 'Get corporation structures',
        params => $params,
        returns => 'ARRAY[GetCorporationsCorporationIdStructures200Ok]',
        };
}
# @return ARRAY[GetCorporationsCorporationIdStructures200Ok]
#
sub get_corporations_corporation_id_structures {
    my ($self, %args) = @_;

    # verify the required parameter 'corporation_id' is set
    unless (exists $args{'corporation_id'}) {
      croak("Missing the required parameter 'corporation_id' when calling get_corporations_corporation_id_structures");
    }

    # parse inputs
    my $_resource_path = '/corporations/{corporation_id}/structures/';

    my $_method = 'GET';
    my $query_params = {};
    my $header_params = {};
    my $form_params = {};

    # 'Accept' and 'Content-Type' header
    my $_header_accept = $self->{api_client}->select_header_accept('application/json');
    if ($_header_accept) {
        $header_params->{'Accept'} = $_header_accept;
    }
    $header_params->{'Content-Type'} = $self->{api_client}->select_header_content_type();

    # query params
    if ( exists $args{'datasource'}) {
        $query_params->{'datasource'} = $self->{api_client}->to_query_value($args{'datasource'});
    }

    # query params
    if ( exists $args{'language'}) {
        $query_params->{'language'} = $self->{api_client}->to_query_value($args{'language'});
    }

    # query params
    if ( exists $args{'page'}) {
        $query_params->{'page'} = $self->{api_client}->to_query_value($args{'page'});
    }

    # query params
    if ( exists $args{'token'}) {
        $query_params->{'token'} = $self->{api_client}->to_query_value($args{'token'});
    }

    # query params
    if ( exists $args{'user_agent'}) {
        $query_params->{'user_agent'} = $self->{api_client}->to_query_value($args{'user_agent'});
    }

    # header params
    if ( exists $args{'x_user_agent'}) {
        $header_params->{'X-User-Agent'} = $self->{api_client}->to_header_value($args{'x_user_agent'});
    }

    # path params
    if ( exists $args{'corporation_id'}) {
        my $_base_variable = "{" . "corporation_id" . "}";
        my $_base_value = $self->{api_client}->to_path_value($args{'corporation_id'});
        $_resource_path =~ s/$_base_variable/$_base_value/g;
    }

    my $_body_data;
    # authentication setting, if any
    my $auth_settings = [qw(evesso )];

    # make the API Call
    my $response = $self->{api_client}->call_api($_resource_path, $_method,
                                           $query_params, $form_params,
                                           $header_params, $_body_data, $auth_settings);
    if (!$response) {
        return;
    }
    my $_response_object = $self->{api_client}->deserialize('ARRAY[GetCorporationsCorporationIdStructures200Ok]', $response);
    return $_response_object;
}

#
# get_corporations_names
#
# Get corporation names
# 
# @param ARRAY[int] $corporation_ids A comma separated list of corporation IDs (required)
# @param string $datasource The server name you would like data from (optional, default to tranquility)
# @param string $user_agent Client identifier, takes precedence over headers (optional)
# @param string $x_user_agent Client identifier, takes precedence over User-Agent (optional)
{
    my $params = {
    'corporation_ids' => {
        data_type => 'ARRAY[int]',
        description => 'A comma separated list of corporation IDs',
        required => '1',
    },
    'datasource' => {
        data_type => 'string',
        description => 'The server name you would like data from',
        required => '0',
    },
    'user_agent' => {
        data_type => 'string',
        description => 'Client identifier, takes precedence over headers',
        required => '0',
    },
    'x_user_agent' => {
        data_type => 'string',
        description => 'Client identifier, takes precedence over User-Agent',
        required => '0',
    },
    };
    __PACKAGE__->method_documentation->{ 'get_corporations_names' } = { 
    	summary => 'Get corporation names',
        params => $params,
        returns => 'ARRAY[GetCorporationsNames200Ok]',
        };
}
# @return ARRAY[GetCorporationsNames200Ok]
#
sub get_corporations_names {
    my ($self, %args) = @_;

    # verify the required parameter 'corporation_ids' is set
    unless (exists $args{'corporation_ids'}) {
      croak("Missing the required parameter 'corporation_ids' when calling get_corporations_names");
    }

    # parse inputs
    my $_resource_path = '/corporations/names/';

    my $_method = 'GET';
    my $query_params = {};
    my $header_params = {};
    my $form_params = {};

    # 'Accept' and 'Content-Type' header
    my $_header_accept = $self->{api_client}->select_header_accept('application/json');
    if ($_header_accept) {
        $header_params->{'Accept'} = $_header_accept;
    }
    $header_params->{'Content-Type'} = $self->{api_client}->select_header_content_type();

    # query params
    if ( exists $args{'corporation_ids'}) {
        $query_params->{'corporation_ids'} = $self->{api_client}->to_query_value($args{'corporation_ids'});
    }

    # query params
    if ( exists $args{'datasource'}) {
        $query_params->{'datasource'} = $self->{api_client}->to_query_value($args{'datasource'});
    }

    # query params
    if ( exists $args{'user_agent'}) {
        $query_params->{'user_agent'} = $self->{api_client}->to_query_value($args{'user_agent'});
    }

    # header params
    if ( exists $args{'x_user_agent'}) {
        $header_params->{'X-User-Agent'} = $self->{api_client}->to_header_value($args{'x_user_agent'});
    }

    my $_body_data;
    # authentication setting, if any
    my $auth_settings = [qw()];

    # make the API Call
    my $response = $self->{api_client}->call_api($_resource_path, $_method,
                                           $query_params, $form_params,
                                           $header_params, $_body_data, $auth_settings);
    if (!$response) {
        return;
    }
    my $_response_object = $self->{api_client}->deserialize('ARRAY[GetCorporationsNames200Ok]', $response);
    return $_response_object;
}

#
# get_corporations_npccorps
#
# Get npc corporations
# 
# @param string $datasource The server name you would like data from (optional, default to tranquility)
# @param string $user_agent Client identifier, takes precedence over headers (optional)
# @param string $x_user_agent Client identifier, takes precedence over User-Agent (optional)
{
    my $params = {
    'datasource' => {
        data_type => 'string',
        description => 'The server name you would like data from',
        required => '0',
    },
    'user_agent' => {
        data_type => 'string',
        description => 'Client identifier, takes precedence over headers',
        required => '0',
    },
    'x_user_agent' => {
        data_type => 'string',
        description => 'Client identifier, takes precedence over User-Agent',
        required => '0',
    },
    };
    __PACKAGE__->method_documentation->{ 'get_corporations_npccorps' } = { 
    	summary => 'Get npc corporations',
        params => $params,
        returns => 'ARRAY[int]',
        };
}
# @return ARRAY[int]
#
sub get_corporations_npccorps {
    my ($self, %args) = @_;

    # parse inputs
    my $_resource_path = '/corporations/npccorps/';

    my $_method = 'GET';
    my $query_params = {};
    my $header_params = {};
    my $form_params = {};

    # 'Accept' and 'Content-Type' header
    my $_header_accept = $self->{api_client}->select_header_accept('application/json');
    if ($_header_accept) {
        $header_params->{'Accept'} = $_header_accept;
    }
    $header_params->{'Content-Type'} = $self->{api_client}->select_header_content_type();

    # query params
    if ( exists $args{'datasource'}) {
        $query_params->{'datasource'} = $self->{api_client}->to_query_value($args{'datasource'});
    }

    # query params
    if ( exists $args{'user_agent'}) {
        $query_params->{'user_agent'} = $self->{api_client}->to_query_value($args{'user_agent'});
    }

    # header params
    if ( exists $args{'x_user_agent'}) {
        $header_params->{'X-User-Agent'} = $self->{api_client}->to_header_value($args{'x_user_agent'});
    }

    my $_body_data;
    # authentication setting, if any
    my $auth_settings = [qw()];

    # make the API Call
    my $response = $self->{api_client}->call_api($_resource_path, $_method,
                                           $query_params, $form_params,
                                           $header_params, $_body_data, $auth_settings);
    if (!$response) {
        return;
    }
    my $_response_object = $self->{api_client}->deserialize('ARRAY[int]', $response);
    return $_response_object;
}

#
# put_corporations_corporation_id_structures_structure_id
#
# Update structure vulnerability schedule
# 
# @param int $corporation_id A corporation ID (required)
# @param ARRAY[PutCorporationsCorporationIdStructuresStructureIdNewSchedule] $new_schedule New vulnerability window schedule for the structure (required)
# @param int $structure_id A structure ID (required)
# @param string $datasource The server name you would like data from (optional, default to tranquility)
# @param string $token Access token to use, if preferred over a header (optional)
# @param string $user_agent Client identifier, takes precedence over headers (optional)
# @param string $x_user_agent Client identifier, takes precedence over User-Agent (optional)
{
    my $params = {
    'corporation_id' => {
        data_type => 'int',
        description => 'A corporation ID',
        required => '1',
    },
    'new_schedule' => {
        data_type => 'ARRAY[PutCorporationsCorporationIdStructuresStructureIdNewSchedule]',
        description => 'New vulnerability window schedule for the structure',
        required => '1',
    },
    'structure_id' => {
        data_type => 'int',
        description => 'A structure ID',
        required => '1',
    },
    'datasource' => {
        data_type => 'string',
        description => 'The server name you would like data from',
        required => '0',
    },
    'token' => {
        data_type => 'string',
        description => 'Access token to use, if preferred over a header',
        required => '0',
    },
    'user_agent' => {
        data_type => 'string',
        description => 'Client identifier, takes precedence over headers',
        required => '0',
    },
    'x_user_agent' => {
        data_type => 'string',
        description => 'Client identifier, takes precedence over User-Agent',
        required => '0',
    },
    };
    __PACKAGE__->method_documentation->{ 'put_corporations_corporation_id_structures_structure_id' } = { 
    	summary => 'Update structure vulnerability schedule',
        params => $params,
        returns => undef,
        };
}
# @return void
#
sub put_corporations_corporation_id_structures_structure_id {
    my ($self, %args) = @_;

    # verify the required parameter 'corporation_id' is set
    unless (exists $args{'corporation_id'}) {
      croak("Missing the required parameter 'corporation_id' when calling put_corporations_corporation_id_structures_structure_id");
    }

    # verify the required parameter 'new_schedule' is set
    unless (exists $args{'new_schedule'}) {
      croak("Missing the required parameter 'new_schedule' when calling put_corporations_corporation_id_structures_structure_id");
    }

    # verify the required parameter 'structure_id' is set
    unless (exists $args{'structure_id'}) {
      croak("Missing the required parameter 'structure_id' when calling put_corporations_corporation_id_structures_structure_id");
    }

    # parse inputs
    my $_resource_path = '/corporations/{corporation_id}/structures/{structure_id}/';

    my $_method = 'PUT';
    my $query_params = {};
    my $header_params = {};
    my $form_params = {};

    # 'Accept' and 'Content-Type' header
    my $_header_accept = $self->{api_client}->select_header_accept('application/json');
    if ($_header_accept) {
        $header_params->{'Accept'} = $_header_accept;
    }
    $header_params->{'Content-Type'} = $self->{api_client}->select_header_content_type();

    # query params
    if ( exists $args{'datasource'}) {
        $query_params->{'datasource'} = $self->{api_client}->to_query_value($args{'datasource'});
    }

    # query params
    if ( exists $args{'token'}) {
        $query_params->{'token'} = $self->{api_client}->to_query_value($args{'token'});
    }

    # query params
    if ( exists $args{'user_agent'}) {
        $query_params->{'user_agent'} = $self->{api_client}->to_query_value($args{'user_agent'});
    }

    # header params
    if ( exists $args{'x_user_agent'}) {
        $header_params->{'X-User-Agent'} = $self->{api_client}->to_header_value($args{'x_user_agent'});
    }

    # path params
    if ( exists $args{'corporation_id'}) {
        my $_base_variable = "{" . "corporation_id" . "}";
        my $_base_value = $self->{api_client}->to_path_value($args{'corporation_id'});
        $_resource_path =~ s/$_base_variable/$_base_value/g;
    }

    # path params
    if ( exists $args{'structure_id'}) {
        my $_base_variable = "{" . "structure_id" . "}";
        my $_base_value = $self->{api_client}->to_path_value($args{'structure_id'});
        $_resource_path =~ s/$_base_variable/$_base_value/g;
    }

    my $_body_data;
    # body params
    if ( exists $args{'new_schedule'}) {
        $_body_data = $args{'new_schedule'};
    }

    # authentication setting, if any
    my $auth_settings = [qw(evesso )];

    # make the API Call
    $self->{api_client}->call_api($_resource_path, $_method,
                                           $query_params, $form_params,
                                           $header_params, $_body_data, $auth_settings);
    return;
}

1;
