=begin comment

EVE Swagger Interface

An OpenAPI for EVE Online

OpenAPI spec version: 0.4.2.dev22

Generated by: https://github.com/swagger-api/swagger-codegen.git

=end comment

=cut

#
# NOTE: This class is auto generated by the swagger code generator program. 
# Do not edit the class manually.
# Ref: https://github.com/swagger-api/swagger-codegen
#
package EVE::ESI::Client::KillmailsApi;

require 5.6.0;
use strict;
use warnings;
use utf8; 
use Exporter;
use Carp qw( croak );
use Log::Any qw($log);

use EVE::ESI::Client::ApiClient;

use base "Class::Data::Inheritable";

__PACKAGE__->mk_classdata('method_documentation' => {});

sub new {
    my $class = shift;
    my $api_client;

    if ($_[0] && ref $_[0] && ref $_[0] eq 'EVE::ESI::Client::ApiClient' ) {
        $api_client = $_[0];
    } else {
        $api_client = EVE::ESI::Client::ApiClient->new(@_);
    }

    bless { api_client => $api_client }, $class;

}


#
# get_characters_character_id_killmails_recent
#
# List kills and losses
# 
# @param int $character_id An EVE character ID (required)
# @param string $datasource The server name you would like data from (optional, default to tranquility)
# @param int $max_count How many killmails to return at maximum (optional, default to 50)
# @param int $max_kill_id Only return killmails with ID smaller than this.  (optional)
# @param string $token Access token to use, if preferred over a header (optional)
# @param string $user_agent Client identifier, takes precedence over headers (optional)
# @param string $x_user_agent Client identifier, takes precedence over User-Agent (optional)
{
    my $params = {
    'character_id' => {
        data_type => 'int',
        description => 'An EVE character ID',
        required => '1',
    },
    'datasource' => {
        data_type => 'string',
        description => 'The server name you would like data from',
        required => '0',
    },
    'max_count' => {
        data_type => 'int',
        description => 'How many killmails to return at maximum',
        required => '0',
    },
    'max_kill_id' => {
        data_type => 'int',
        description => 'Only return killmails with ID smaller than this. ',
        required => '0',
    },
    'token' => {
        data_type => 'string',
        description => 'Access token to use, if preferred over a header',
        required => '0',
    },
    'user_agent' => {
        data_type => 'string',
        description => 'Client identifier, takes precedence over headers',
        required => '0',
    },
    'x_user_agent' => {
        data_type => 'string',
        description => 'Client identifier, takes precedence over User-Agent',
        required => '0',
    },
    };
    __PACKAGE__->method_documentation->{ 'get_characters_character_id_killmails_recent' } = { 
    	summary => 'List kills and losses',
        params => $params,
        returns => 'ARRAY[GetCharactersCharacterIdKillmailsRecent200Ok]',
        };
}
# @return ARRAY[GetCharactersCharacterIdKillmailsRecent200Ok]
#
sub get_characters_character_id_killmails_recent {
    my ($self, %args) = @_;

    # verify the required parameter 'character_id' is set
    unless (exists $args{'character_id'}) {
      croak("Missing the required parameter 'character_id' when calling get_characters_character_id_killmails_recent");
    }

    # parse inputs
    my $_resource_path = '/characters/{character_id}/killmails/recent/';

    my $_method = 'GET';
    my $query_params = {};
    my $header_params = {};
    my $form_params = {};

    # 'Accept' and 'Content-Type' header
    my $_header_accept = $self->{api_client}->select_header_accept('application/json');
    if ($_header_accept) {
        $header_params->{'Accept'} = $_header_accept;
    }
    $header_params->{'Content-Type'} = $self->{api_client}->select_header_content_type();

    # query params
    if ( exists $args{'datasource'}) {
        $query_params->{'datasource'} = $self->{api_client}->to_query_value($args{'datasource'});
    }

    # query params
    if ( exists $args{'max_count'}) {
        $query_params->{'max_count'} = $self->{api_client}->to_query_value($args{'max_count'});
    }

    # query params
    if ( exists $args{'max_kill_id'}) {
        $query_params->{'max_kill_id'} = $self->{api_client}->to_query_value($args{'max_kill_id'});
    }

    # query params
    if ( exists $args{'token'}) {
        $query_params->{'token'} = $self->{api_client}->to_query_value($args{'token'});
    }

    # query params
    if ( exists $args{'user_agent'}) {
        $query_params->{'user_agent'} = $self->{api_client}->to_query_value($args{'user_agent'});
    }

    # header params
    if ( exists $args{'x_user_agent'}) {
        $header_params->{'X-User-Agent'} = $self->{api_client}->to_header_value($args{'x_user_agent'});
    }

    # path params
    if ( exists $args{'character_id'}) {
        my $_base_variable = "{" . "character_id" . "}";
        my $_base_value = $self->{api_client}->to_path_value($args{'character_id'});
        $_resource_path =~ s/$_base_variable/$_base_value/g;
    }

    my $_body_data;
    # authentication setting, if any
    my $auth_settings = [qw(evesso )];

    # make the API Call
    my $response = $self->{api_client}->call_api($_resource_path, $_method,
                                           $query_params, $form_params,
                                           $header_params, $_body_data, $auth_settings);
    if (!$response) {
        return;
    }
    my $_response_object = $self->{api_client}->deserialize('ARRAY[GetCharactersCharacterIdKillmailsRecent200Ok]', $response);
    return $_response_object;
}

#
# get_killmails_killmail_id_killmail_hash
#
# Get a single killmail
# 
# @param string $killmail_hash The killmail hash for verification (required)
# @param int $killmail_id The killmail ID to be queried (required)
# @param string $datasource The server name you would like data from (optional, default to tranquility)
# @param string $user_agent Client identifier, takes precedence over headers (optional)
# @param string $x_user_agent Client identifier, takes precedence over User-Agent (optional)
{
    my $params = {
    'killmail_hash' => {
        data_type => 'string',
        description => 'The killmail hash for verification',
        required => '1',
    },
    'killmail_id' => {
        data_type => 'int',
        description => 'The killmail ID to be queried',
        required => '1',
    },
    'datasource' => {
        data_type => 'string',
        description => 'The server name you would like data from',
        required => '0',
    },
    'user_agent' => {
        data_type => 'string',
        description => 'Client identifier, takes precedence over headers',
        required => '0',
    },
    'x_user_agent' => {
        data_type => 'string',
        description => 'Client identifier, takes precedence over User-Agent',
        required => '0',
    },
    };
    __PACKAGE__->method_documentation->{ 'get_killmails_killmail_id_killmail_hash' } = { 
    	summary => 'Get a single killmail',
        params => $params,
        returns => 'GetKillmailsKillmailIdKillmailHashOk',
        };
}
# @return GetKillmailsKillmailIdKillmailHashOk
#
sub get_killmails_killmail_id_killmail_hash {
    my ($self, %args) = @_;

    # verify the required parameter 'killmail_hash' is set
    unless (exists $args{'killmail_hash'}) {
      croak("Missing the required parameter 'killmail_hash' when calling get_killmails_killmail_id_killmail_hash");
    }

    # verify the required parameter 'killmail_id' is set
    unless (exists $args{'killmail_id'}) {
      croak("Missing the required parameter 'killmail_id' when calling get_killmails_killmail_id_killmail_hash");
    }

    # parse inputs
    my $_resource_path = '/killmails/{killmail_id}/{killmail_hash}/';

    my $_method = 'GET';
    my $query_params = {};
    my $header_params = {};
    my $form_params = {};

    # 'Accept' and 'Content-Type' header
    my $_header_accept = $self->{api_client}->select_header_accept('application/json');
    if ($_header_accept) {
        $header_params->{'Accept'} = $_header_accept;
    }
    $header_params->{'Content-Type'} = $self->{api_client}->select_header_content_type();

    # query params
    if ( exists $args{'datasource'}) {
        $query_params->{'datasource'} = $self->{api_client}->to_query_value($args{'datasource'});
    }

    # query params
    if ( exists $args{'user_agent'}) {
        $query_params->{'user_agent'} = $self->{api_client}->to_query_value($args{'user_agent'});
    }

    # header params
    if ( exists $args{'x_user_agent'}) {
        $header_params->{'X-User-Agent'} = $self->{api_client}->to_header_value($args{'x_user_agent'});
    }

    # path params
    if ( exists $args{'killmail_hash'}) {
        my $_base_variable = "{" . "killmail_hash" . "}";
        my $_base_value = $self->{api_client}->to_path_value($args{'killmail_hash'});
        $_resource_path =~ s/$_base_variable/$_base_value/g;
    }

    # path params
    if ( exists $args{'killmail_id'}) {
        my $_base_variable = "{" . "killmail_id" . "}";
        my $_base_value = $self->{api_client}->to_path_value($args{'killmail_id'});
        $_resource_path =~ s/$_base_variable/$_base_value/g;
    }

    my $_body_data;
    # authentication setting, if any
    my $auth_settings = [qw()];

    # make the API Call
    my $response = $self->{api_client}->call_api($_resource_path, $_method,
                                           $query_params, $form_params,
                                           $header_params, $_body_data, $auth_settings);
    if (!$response) {
        return;
    }
    my $_response_object = $self->{api_client}->deserialize('GetKillmailsKillmailIdKillmailHashOk', $response);
    return $_response_object;
}

1;
